spring.application.name=user-service
server.port=8082

# -------------------------------------------------------
# BASE DE DATOS
# Cambiar los siguientes valores una vez tengas MySQL listo
# Crear la base de datos con: CREATE DATABASE worki_user_db;
# -------------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/worki_user_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -------------------------------------------------------
# JPA / HIBERNATE
# ddl-auto=update crea/actualiza las tablas automáticamente
# Cambiar a validate o none en producción
# -------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
